-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 05:02:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web_pos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_pos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `web_pos` ;

-- -----------------------------------------------------
-- Table `web_pos`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_pos`.`customer` (
  `id` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `salary` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `web_pos`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_pos`.`item` (
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `qty` INT NOT NULL,
  `unit_price` DOUBLE NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `web_pos`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_pos`.`orders` (
  `oid` VARCHAR(255) NOT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `customerid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `FKbhieamq65ke02r8ijfso5tivn` (`customerid` ASC) VISIBLE,
  CONSTRAINT `FKbhieamq65ke02r8ijfso5tivn`
    FOREIGN KEY (`customerid`)
    REFERENCES `web_pos`.`customer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `web_pos`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_pos`.`order_details` (
  `item_code` VARCHAR(255) NOT NULL,
  `oid` VARCHAR(255) NOT NULL,
  `qty` INT NOT NULL,
  `unit_price` DOUBLE NOT NULL,
  PRIMARY KEY (`item_code`, `oid`),
  INDEX `FKrocfvt7nbxmbuvomvlac7dxcq` (`oid` ASC) VISIBLE,
  CONSTRAINT `FKiu11dn39w4ejb2b9swl1ir1bw`
    FOREIGN KEY (`item_code`)
    REFERENCES `web_pos`.`item` (`code`),
  CONSTRAINT `FKrocfvt7nbxmbuvomvlac7dxcq`
    FOREIGN KEY (`oid`)
    REFERENCES `web_pos`.`orders` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `web_pos`.`order_item_pk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_pos`.`order_item_pk` (
  `oid` VARCHAR(255) NOT NULL,
  `item_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
